### PR TITLE
added material-ui and semantic-ui

### PR DESCRIPTION
**Pull request by fnnzzz**

### CODE REVIEW

**Comment by sapegin** [comment]
Have you used both an like them?

**Comment by fnnzzz** [comment]
1) Used Material-UI in the two projects, everything is fine. But it seems with version 15.3 React started swearing at Custom HTML Props, It's possible to have corrected.
2) With Semantic, too, all is well in my experience
3) On the Semantic made a couple of presentations, all comfortable and beautiful
4) Griddle not tried it, but they say great

**Comment by sapegin** [comment]
Then I’d suggest to remove Griddle ;-) And I don’t know where to put Spectacle, not even sure it’s in the scope of the list — it’s called “React Components Catalog” by the way.

**Comment by fnnzzz** [comment]
okey, Griddle is deleted. 
Spectacle provides to the various components, such as Slide, Quote, CodePane, Tables, List etc.
If you are on this, I move it to the "Miscellaneous"

**Comment by sapegin** [comment]
> If you are on this, I move it to the "Miscellaneous"

Sound good ;-)

**Pull request merged**
